/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.culminating.calculator;

/**
 *
 * @author eljas
 */
public class altcolour1 extends javax.swing.JFrame {
        int anum1 = 0;
        int anum2 = 0;
        int aoperator = 0;
    
    /**
     * Creates new form altcolour1
     */
    public altcolour1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abtn8 = new javax.swing.JButton();
        abtn7 = new javax.swing.JButton();
        abtnx = new javax.swing.JButton();
        abtn4 = new javax.swing.JButton();
        abtn5 = new javax.swing.JButton();
        abtn6 = new javax.swing.JButton();
        abtnminus = new javax.swing.JButton();
        abtn1 = new javax.swing.JButton();
        abtn2 = new javax.swing.JButton();
        abtn3 = new javax.swing.JButton();
        abtnplus = new javax.swing.JButton();
        abtn0 = new javax.swing.JButton();
        abtn9 = new javax.swing.JButton();
        abtndiv = new javax.swing.JButton();
        abtnequals = new javax.swing.JButton();
        abtnchnggui = new javax.swing.JButton();
        albltop = new javax.swing.JLabel();
        altbtnc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abtn8.setBackground(new java.awt.Color(0, 0, 0));
        abtn8.setForeground(new java.awt.Color(255, 255, 255));
        abtn8.setText("8");
        abtn8.setAutoscrolls(true);
        abtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn8ActionPerformed(evt);
            }
        });

        abtn7.setBackground(new java.awt.Color(0, 0, 0));
        abtn7.setForeground(new java.awt.Color(255, 255, 255));
        abtn7.setText("7");
        abtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn7ActionPerformed(evt);
            }
        });

        abtnx.setBackground(new java.awt.Color(0, 0, 0));
        abtnx.setForeground(new java.awt.Color(255, 255, 255));
        abtnx.setText("x");
        abtnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnxActionPerformed(evt);
            }
        });

        abtn4.setBackground(new java.awt.Color(0, 0, 0));
        abtn4.setForeground(new java.awt.Color(255, 255, 255));
        abtn4.setText("4");
        abtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn4ActionPerformed(evt);
            }
        });

        abtn5.setBackground(new java.awt.Color(0, 0, 0));
        abtn5.setForeground(new java.awt.Color(255, 255, 255));
        abtn5.setText("5");
        abtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn5ActionPerformed(evt);
            }
        });

        abtn6.setBackground(new java.awt.Color(0, 0, 0));
        abtn6.setForeground(new java.awt.Color(255, 255, 255));
        abtn6.setText("6");
        abtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn6ActionPerformed(evt);
            }
        });

        abtnminus.setBackground(new java.awt.Color(0, 0, 0));
        abtnminus.setForeground(new java.awt.Color(255, 255, 255));
        abtnminus.setText("-");
        abtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnminusActionPerformed(evt);
            }
        });

        abtn1.setBackground(new java.awt.Color(0, 0, 0));
        abtn1.setForeground(new java.awt.Color(255, 255, 255));
        abtn1.setText("1");
        abtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn1ActionPerformed(evt);
            }
        });

        abtn2.setBackground(new java.awt.Color(0, 0, 0));
        abtn2.setForeground(new java.awt.Color(255, 255, 255));
        abtn2.setText("2");
        abtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn2ActionPerformed(evt);
            }
        });

        abtn3.setBackground(new java.awt.Color(0, 0, 0));
        abtn3.setForeground(new java.awt.Color(255, 255, 255));
        abtn3.setText("3");
        abtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn3ActionPerformed(evt);
            }
        });

        abtnplus.setBackground(new java.awt.Color(0, 0, 0));
        abtnplus.setForeground(new java.awt.Color(255, 255, 255));
        abtnplus.setText("+");
        abtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnplusActionPerformed(evt);
            }
        });

        abtn0.setBackground(new java.awt.Color(0, 0, 0));
        abtn0.setForeground(new java.awt.Color(255, 255, 255));
        abtn0.setText("0");
        abtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn0ActionPerformed(evt);
            }
        });

        abtn9.setBackground(new java.awt.Color(0, 0, 0));
        abtn9.setForeground(new java.awt.Color(255, 255, 255));
        abtn9.setText("9");
        abtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtn9ActionPerformed(evt);
            }
        });

        abtndiv.setBackground(new java.awt.Color(0, 0, 0));
        abtndiv.setForeground(new java.awt.Color(255, 255, 255));
        abtndiv.setText("/");
        abtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtndivActionPerformed(evt);
            }
        });

        abtnequals.setBackground(new java.awt.Color(0, 0, 0));
        abtnequals.setForeground(new java.awt.Color(255, 255, 255));
        abtnequals.setText("=");
        abtnequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnequalsActionPerformed(evt);
            }
        });

        abtnchnggui.setBackground(new java.awt.Color(0, 0, 0));
        abtnchnggui.setForeground(new java.awt.Color(255, 255, 255));
        abtnchnggui.setText("Switch colour");
        abtnchnggui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnchngguiActionPerformed(evt);
            }
        });

        albltop.setBackground(new java.awt.Color(0, 0, 0));
        albltop.setText("-");
        albltop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        altbtnc.setBackground(new java.awt.Color(0, 0, 0));
        altbtnc.setForeground(new java.awt.Color(255, 255, 255));
        altbtnc.setText("C");
        altbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altbtncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(albltop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abtnchnggui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abtnequals))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abtn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtn9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtnx))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abtn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtnminus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abtnplus)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(altbtnc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abtndiv)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(albltop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abtndiv)
                    .addComponent(altbtnc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abtn7)
                    .addComponent(abtn8)
                    .addComponent(abtnx)
                    .addComponent(abtn9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abtn4)
                    .addComponent(abtn5)
                    .addComponent(abtn6)
                    .addComponent(abtnminus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abtn1)
                    .addComponent(abtn2)
                    .addComponent(abtn3)
                    .addComponent(abtnplus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abtn0)
                    .addComponent(abtnequals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abtnchnggui)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnplusActionPerformed
        // TODO add your handling code here:
        albltop.setText("+");
        aoperator= 1 ;
    }//GEN-LAST:event_abtnplusActionPerformed

    private void abtnchngguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnchngguiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Firstcalcualtorpage().setVisible(true);
        
    }//GEN-LAST:event_abtnchngguiActionPerformed

    private void altbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altbtncActionPerformed
        // TODO add your handling code here:
        albltop.setText("-");
        anum1 = 0;
        anum2 = 0;
        aoperator= 0;        
    }//GEN-LAST:event_altbtncActionPerformed

    private void abtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtndivActionPerformed
        // TODO add your handling code here:
        albltop.setText("/");
        aoperator= 4 ;
    }//GEN-LAST:event_abtndivActionPerformed

    private void abtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn7ActionPerformed
        // TODO add your handling code here:
        albltop.setText("7");
        if (anum1 == 0) {
            anum1 = 7;
        }
        else if (anum1 != 0) {
            anum2 = 7;
        }
    }//GEN-LAST:event_abtn7ActionPerformed

    private void abtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn8ActionPerformed
        // TODO add your handling code here:
        albltop.setText("8");
        if (anum1 == 0) {
            anum1 = 8;
        }
        else if (anum1 != 0) {
            anum2 = 8;
        }
    }//GEN-LAST:event_abtn8ActionPerformed

    private void abtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn9ActionPerformed
        // TODO add your handling code here:
        albltop.setText("9");
        if (anum1 == 0) {
            anum1 = 9;
        }
        else if (anum1 != 0) {
            anum2 = 9;
        }
    }//GEN-LAST:event_abtn9ActionPerformed

    private void abtnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnxActionPerformed
        // TODO add your handling code here:
        albltop.setText("x");
        aoperator= 3 ;        
    }//GEN-LAST:event_abtnxActionPerformed

    private void abtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn4ActionPerformed
        // TODO add your handling code here:
        albltop.setText("4");
        if (anum1 == 0) {
            anum1 = 4;
        }
        else if (anum1 != 0) {
            anum2 = 4;
        }
    }//GEN-LAST:event_abtn4ActionPerformed

    private void abtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn5ActionPerformed
        // TODO add your handling code here:
        albltop.setText("5");
        if (anum1 == 0) {
            anum1 = 5;
        }
        else if (anum1 != 0) {
            anum2 = 5;
        }
    }//GEN-LAST:event_abtn5ActionPerformed

    private void abtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn6ActionPerformed
        // TODO add your handling code here:
        albltop.setText("6");
        if (anum1 == 0) {
            anum1 = 6;
        }
        else if (anum1 != 0) {
            anum2 = 6;
        }
    }//GEN-LAST:event_abtn6ActionPerformed

    private void abtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnminusActionPerformed
        // TODO add your handling code here:
        albltop.setText("-");
        aoperator= 2 ;
    }//GEN-LAST:event_abtnminusActionPerformed

    private void abtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn1ActionPerformed
        // TODO add your handling code here:
        albltop.setText("1");
        if (anum1 == 0) {
            anum1 = 1;
        }
        else if (anum1 != 0) {
            anum2 = 1;
        }
    }//GEN-LAST:event_abtn1ActionPerformed

    private void abtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn2ActionPerformed
        // TODO add your handling code here:
        albltop.setText("2");
        if (anum1 == 0) {
            anum1 = 2;
        }
        else if (anum1 != 0) {
            anum2 = 2;
        }
    }//GEN-LAST:event_abtn2ActionPerformed

    private void abtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn3ActionPerformed
        // TODO add your handling code here:
        albltop.setText("3");
        if (anum1 == 0) {
            anum1 = 3;
        }
        else if (anum1 != 0) {
            anum2 = 3;
        }
    }//GEN-LAST:event_abtn3ActionPerformed

    private void abtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtn0ActionPerformed
        // TODO add your handling code here:
        albltop.setText("0");
        if (anum1 == 0) {
            anum1 = 0;
        }
        else if (anum1 != 0) {
            anum2 = 0;
        }
    }//GEN-LAST:event_abtn0ActionPerformed

    private void abtnequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnequalsActionPerformed
        // TODO add your handling code here:
        if (aoperator == 4){
        double anwser = (anum1 / anum2);
        String stranwser = String.valueOf(anwser);
        albltop.setText(stranwser);
        anum1 = 0;
        anum2 = 0;
        aoperator= 0 ;
        }
        else if (aoperator == 3){
        double anwser = (anum1 * anum2);
        String stranwser = String.valueOf(anwser);
        albltop.setText(stranwser);
        anum1 = 0;
        anum2 = 0;
        aoperator= 0 ;
        }
        else if (aoperator == 2){
        double anwser = (anum1 - anum2);
        String stranwser = String.valueOf(anwser);
        albltop.setText(stranwser);
        anum1 = 0;
        anum2 = 0;
        aoperator= 0 ;
        }
        else if (aoperator == 1 ){
        double anwser = (anum1 + anum2);
        String stranwser = String.valueOf(anwser);
        albltop.setText(stranwser);
        anum1 = 0;
        anum2 = 0;
        aoperator= 0;
        }
        else {
            albltop.setText("error try again");
        }    
    }//GEN-LAST:event_abtnequalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altcolour1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altcolour1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altcolour1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altcolour1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altcolour1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abtn0;
    private javax.swing.JButton abtn1;
    private javax.swing.JButton abtn2;
    private javax.swing.JButton abtn3;
    private javax.swing.JButton abtn4;
    private javax.swing.JButton abtn5;
    private javax.swing.JButton abtn6;
    private javax.swing.JButton abtn7;
    private javax.swing.JButton abtn8;
    private javax.swing.JButton abtn9;
    private javax.swing.JButton abtnchnggui;
    private javax.swing.JButton abtndiv;
    private javax.swing.JButton abtnequals;
    private javax.swing.JButton abtnminus;
    private javax.swing.JButton abtnplus;
    private javax.swing.JButton abtnx;
    private javax.swing.JLabel albltop;
    private javax.swing.JButton altbtnc;
    // End of variables declaration//GEN-END:variables
}
